name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - 'feature/**'
      - 'develop'
    branches-ignore:
      - 'main'
permissions:
  contents: write
  pull-requests: write
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed' || github.event_name == 'push'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: deploy
          preview-url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.number || github.run_number }}/
  remove-preview:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed' && github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Remove PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove
          preview-url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.number }}/
        continue-on-error: true